name: Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id_token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.pages_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Setup .Net
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 8.0.x
            
            - name: Install .net wasm tools
              run: dotnet workload install wasm-tools

            - name: restore dependencies
              run: dotnet restore

            - name: build
              run: dotnet build -c Release --no-restore

            - name: Publish
                run: dotnet publish BlazorDeploy.csproj -c Release -o docs --no-logo  --no-restore


            - name: setup pages
              uses: actions/configure-pages@v4

            - name: upload
              id: deployment
              uses: actions/deploy-pages@v4

